services:
  - type: web
    name: lexus-contable
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: ADMIN_USER
        value: Joel777
      - key: ADMIN_PASS
        value: 585858
