services:
  - type: web
    name: jnj-srl-contable
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: ADMIN_USER
        value: Joel777
      - key: ADMIN_PASS
        value: 585858
